
:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font


= Watson Visual Recognition Connector API Reference

+++
Visual Recognition allows users to understand the contents of an image or video frame, answering the question: “What
is in this image?” Submit an image, and the service returns scores for relevant classifiers representing things such
as objects, events and settings.
+++

*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| Requires Mule Enterprise License |  Yes icon:star[]  {nbsp}
| Requires Entitlement |  No icon:remove[]  {nbsp}
| Mule Version | 3.6.0 or higher
|======================


== Configs
---
=== Configuration
`<watson-visual-recognition:config>`


`Connection Management` 



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| apiKey | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Your API key.+++ |   | *x*{nbsp}
| versionDate | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The release date of the version of the API you want to use. Specify dates in YYYY-MM-DD format. The current version is 2016-05-20.+++ |  2016-05-20 | {nbsp}
|======================



== Processors

---

=== Classify an Image
`<watson-visual-recognition:classify-image>`




+++
Upload images or URLs to identify built-in classifiers by default. To identify custom classifiers, include the
classifier_ids parameters. Images must be in .jpeg, or .png format.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#classify_an_image">API Doc</a>
+++

==== XML Sample
[source,xml]
----
<watson-visual-recognition:classify-image config-ref="Watson_Visual_Recognition__Configuration" 
	equest-ref="#[flowVars.request]" />
----

    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ClassifyImageRequest.html">ClassifyImageRequest</a>+++ | +++Request object that contains the image and the classifier to be use.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++VisualClassification+++ | +++A object containing the list of detected classes in the image.+++
|======================




---

=== Detect Faces
`<watson-visual-recognition:detect-faces>`




+++
Analyze faces in images and get data about them, such as estimated age and gender. Images must be in .jpeg, or
.png format.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#classify_an_image">API Doc</a>
+++

==== XML Sample
[source,xml]
----
<watson-visual-recognition:detect-faces config-ref="Watson_Visual_Recognition__Configuration"
	request-ref="#[flowVars.request]" />
----

    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ImageRequest.html">ImageRequest</a>+++ | +++Request object that contains the image to be use.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DetectedFaces+++ | +++A object containing the list of detected faces, age, gender and position in the image.+++
|======================




---

=== Recognize Text
`<watson-visual-recognition:recognize-text>`




+++
Recognizes text in images. This is a beta function of the Visual Recognition service that supports only English
language text identification.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#recognize_text">API Doc</a>
+++

==== XML Sample
[source,xml]
----
<watson-visual-recognition:recognize-text config-ref="Watson_Visual_Recognition__Configuration"
	request-ref="#[flowVars.request]" />
----

    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ImageRequest.html">ImageRequest</a>+++ | +++Request object that contains the image to be use.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++RecognizedText+++ | +++The text recognized in the image.+++
|======================




---

=== Retrieve the List of Classifiers
`<watson-visual-recognition:retrieve-list-of-classifiers>`




+++
Retrieve a list of user-created classifiers.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#create_a_classifier">API
Doc</a>
+++

==== XML Sample
[source,xml]
----
<watson-visual-recognition:retrieve-list-of-classifiers config-ref="Watson_Visual_Recognition__Configuration"/>
----

    

==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}

|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><VisualClassifier>+++ | +++A list of classifiers associated with your API Key.+++
|======================




---

=== Retrieve Classifier Details
`<watson-visual-recognition:retrieve-classifier-details>`




+++
Retrieve information about a specific classifier.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#retrieve_classifier_details">
API Doc</a>
+++

==== XML Sample
[source,xml]
----
<watson-visual-recognition:retrieve-classifier-details config-ref="Watson_Visual_Recognition__Configuration"
	classifierId="8fce44082c5d4c98a965bf2c8aa249ea" />
----

    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
classifierId icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The ID of the classifier for which you want details.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++VisualClassifier+++ | +++A classifier associated with your API Key.+++
|======================




---

=== Delete a Classifier
`<watson-visual-recognition:delete-classifier>`




+++
Delete a custom classifier with the specified classifier ID.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#delete_a_classifier">API
Doc</a>
+++

==== XML Sample
[source,xml]
----
<watson-visual-recognition:delete-classifier config-ref="Watson_Visual_Recognition__Configuration"
	classifierId="8fce44082c5d4c98a965bf2c8aa249ea" />
----

    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
classifierId icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The ID of the classifier you want to delete.+++ | #[payload] | {nbsp}


|======================





---

=== Create a Classifier
`<watson-visual-recognition:create-classifier>`




+++
Train a new multi-faceted classifier on the uploaded image data. A new custom classifier can be trained by
several compressed (.zip) files, including files containing positive or negative images (.jpg, or .png). You must
supply at least two compressed files, either two positive example files or one positive and one negative example
file.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?java#create_a_classifier">API
Doc</a>
+++

==== XML Sample
[source,xml]
----
<watson-visual-recognition:create-classifier config-ref="Watson_Visual_Recognition__Configuration"
	request-ref="#[flowVars.request]" />
----

    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ClassifierRequest.html">ClassifierRequest</a>+++ | +++Request object that contains the classifier name, the positive examples and the negative examples to be use during the creation of the classifier.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++VisualClassifier+++ | +++The classifier that was created.+++
|======================














