
:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font


= Watson Visual Recognition Connector API Reference

+++
Visual Recognition allows users to understand the contents of an image or video frame, answering the question: “What
is in this image?” Submit an image, and the service returns scores for relevant classifiers representing things such
as objects, events and settings.
+++

*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| Requires Mule Enterprise License |  Yes icon:star[]  {nbsp}
| Requires Entitlement |  No icon:remove[]  {nbsp}
| Mule Version | 3.6.0 or higher
|======================


== Configs
---
=== Configuration
`<watson-visual-recognition:config>`


`Connection Management` 



==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| apiKey | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++A apiKey+++ |   | *x*{nbsp}
| versionDate | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++Version date of the API+++ |  2016-05-20 | {nbsp}
|======================



== Processors

---

=== Classify image
`<watson-visual-recognition:classify-image>`




+++
Upload images or URLs to identify built-in classifiers by default. To identify custom classifiers, include the
classifier_ids parameters. Images must be in .jpeg, or .png format.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#classify_an_image">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ClassifyImageRequest.html">ClassifyImageRequest</a>+++ | +++Request with all the options for the classify an image operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++VisualClassification+++ | +++A list of detected classes in the image.+++
|======================




---

=== Detect faces
`<watson-visual-recognition:detect-faces>`




+++
Analyze faces in images and get data about them, such as estimated age and gender. Images must be in .jpeg, or
.png format.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#classify_an_image">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ImageRequest.html">ImageRequest</a>+++ | +++Request with all the options for the detect faces operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++DetectedFaces+++ | +++A list of detected faces, his age, gender and position in the image.+++
|======================




---

=== Recognize text
`<watson-visual-recognition:recognize-text>`




+++
Recognizes text in images. This is a beta function of the Visual Recognition service that supports only English
language text identification.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#recognize_text">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ImageRequest.html">ImageRequest</a>+++ | +++Request with all the options for the recognize text operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++RecognizedText+++ | +++The text recognized in the image.+++
|======================




---

=== Retrieve list of classifiers
`<watson-visual-recognition:retrieve-list-of-classifiers>`




+++
Retrieve a list of user-created classifiers.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#create_a_classifier">API
Doc</a>
+++


    

==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}

|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/List.html">List</a><VisualClassifier>+++ | +++A list of classifiers associated with your API Key.+++
|======================




---

=== Retrieve classifier details
`<watson-visual-recognition:retrieve-classifier-details>`




+++
Retrieve information about a specific classifier.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#retrieve_classifier_details">
API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
classifierId icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The ID of the classifier for which you want details.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++VisualClassifier+++ | +++A classifier associated with your API Key.+++
|======================




---

=== Delete classifier
`<watson-visual-recognition:delete-classifier>`




+++
Delete a custom classifier with the specified classifier ID.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?curl#delete_a_classifier">API
Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
classifierId icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The ID of the classifier you want to delete.+++ | #[payload] | {nbsp}


|======================





---

=== Create classifier
`<watson-visual-recognition:create-classifier>`




+++
Train a new multi-faceted classifier on the uploaded image data. A new custom classifier can be trained by
several compressed (.zip) files, including files containing positive or negative images (.jpg, or .png). You must
supply at least two compressed files, either two positive example files or one positive and one negative example
file.
<a href="http://www.ibm.com/watson/developercloud/visual-recognition/api/v3/?java#create_a_classifier">API
Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ClassifierRequest.html">ClassifierRequest</a>+++ | +++Request with all the options for the create classifier operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++VisualClassifier+++ | +++The classifier that was created.+++
|======================




---

=== Update classifier
`<watson-visual-recognition:update-classifier>`




+++
Update an existing classifier by adding new classes, or by adding new images to existing classes
<a href="https://www.ibm.com/watson/developercloud/visual-recognition/api/v3/#update_a_classifier">API Doc</a>
+++


    
    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
request icon:envelope[] | +++<a href="javadocs/org/mule/modules/watsonvisualrecognition/model/ClassifierRequest.html">ClassifierRequest</a>+++ | +++Request with all the options for the update classifier operation.+++ | #[payload] | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++VisualClassifier+++ | +++The classifier that was updated.+++
|======================




---

=== Byte array to file
`<watson-visual-recognition:byte-array-to-file>`




+++
Convert an array of bytes into a File object to use it in the other operations.
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
data icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++The array of byte to convert.+++ | #[payload] | {nbsp}




| 
extension  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The extension of the file you want to create.+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/io/File.html">File</a>+++ | +++return A temporal file with the contend of the byte array.+++
|======================




---

=== Input stream to file
`<watson-visual-recognition:input-stream-to-file>`




+++
Convert an array of bytes into a File object to use it in the other operations.
+++


    
        
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
data icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html">InputStream</a>+++ | +++The InputStream to convert.+++ | #[payload] | {nbsp}




| 
extension  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The extension of the file you want to create.+++ |  | *x*{nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/io/File.html">File</a>+++ | +++return A temporal file with the contend of the InputStream.+++
|======================














